//
// Generated file com/nutanix/dataprotection/v4/error/error.proto.
//
// Product version: 16.9.0-SNAPSHOT
//
// Part of the Nutanix Data Proetction gRPC APIs
//
// (c) 2024 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: com/nutanix/dataprotection/v4/error/error.proto

package error

import (
	config "github.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/common/v1/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppMessage struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Message       string                                        `protobuf:"bytes,201,opt,name=message,proto3" json:"message,omitempty"`
	Severity      config.MessageSeverityMessage_MessageSeverity `protobuf:"varint,202,opt,name=severity,proto3,enum=com.nutanix.common.v1.config.MessageSeverityMessage_MessageSeverity" json:"severity,omitempty"`
	Code          string                                        `protobuf:"bytes,203,opt,name=code,proto3" json:"code,omitempty"`
	Locale        string                                        `protobuf:"bytes,204,opt,name=locale,proto3" json:"locale,omitempty"`
	ErrorGroup    string                                        `protobuf:"bytes,205,opt,name=error_group,json=errorGroup,proto3" json:"error_group,omitempty"`
	ArgumentsMap  map[string]string                             `protobuf:"bytes,206,rep,name=arguments_map,json=argumentsMap,proto3" json:"arguments_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMessage) Reset() {
	*x = AppMessage{}
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMessage) ProtoMessage() {}

func (x *AppMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMessage.ProtoReflect.Descriptor instead.
func (*AppMessage) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP(), []int{0}
}

func (x *AppMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AppMessage) GetSeverity() config.MessageSeverityMessage_MessageSeverity {
	if x != nil {
		return x.Severity
	}
	return config.MessageSeverityMessage_MessageSeverity(0)
}

func (x *AppMessage) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AppMessage) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *AppMessage) GetErrorGroup() string {
	if x != nil {
		return x.ErrorGroup
	}
	return ""
}

func (x *AppMessage) GetArgumentsMap() map[string]string {
	if x != nil {
		return x.ArgumentsMap
	}
	return nil
}

type AppMessageArrayWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*AppMessage          `protobuf:"bytes,1000,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMessageArrayWrapper) Reset() {
	*x = AppMessageArrayWrapper{}
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMessageArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMessageArrayWrapper) ProtoMessage() {}

func (x *AppMessageArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMessageArrayWrapper.ProtoReflect.Descriptor instead.
func (*AppMessageArrayWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP(), []int{1}
}

func (x *AppMessageArrayWrapper) GetValue() []*AppMessage {
	if x != nil {
		return x.Value
	}
	return nil
}

type SchemaValidationErrorWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *SchemaValidationError `protobuf:"bytes,1000,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaValidationErrorWrapper) Reset() {
	*x = SchemaValidationErrorWrapper{}
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaValidationErrorWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaValidationErrorWrapper) ProtoMessage() {}

func (x *SchemaValidationErrorWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaValidationErrorWrapper.ProtoReflect.Descriptor instead.
func (*SchemaValidationErrorWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP(), []int{2}
}

func (x *SchemaValidationErrorWrapper) GetValue() *SchemaValidationError {
	if x != nil {
		return x.Value
	}
	return nil
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This schema is auto-generated by the Open API Dev Platform as REST response for 4xx and 5xx error responses.
	//
	// Types that are valid to be assigned to Error:
	//
	//	*ErrorResponse_AppMessageArrayError
	//	*ErrorResponse_SchemaValidationErrorError
	Error         isErrorResponse_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetError() isErrorResponse_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ErrorResponse) GetAppMessageArrayError() *AppMessageArrayWrapper {
	if x != nil {
		if x, ok := x.Error.(*ErrorResponse_AppMessageArrayError); ok {
			return x.AppMessageArrayError
		}
	}
	return nil
}

func (x *ErrorResponse) GetSchemaValidationErrorError() *SchemaValidationErrorWrapper {
	if x != nil {
		if x, ok := x.Error.(*ErrorResponse_SchemaValidationErrorError); ok {
			return x.SchemaValidationErrorError
		}
	}
	return nil
}

type isErrorResponse_Error interface {
	isErrorResponse_Error()
}

type ErrorResponse_AppMessageArrayError struct {
	AppMessageArrayError *AppMessageArrayWrapper `protobuf:"bytes,201,opt,name=app_message_array_error,json=appMessageArrayError,proto3,oneof"`
}

type ErrorResponse_SchemaValidationErrorError struct {
	SchemaValidationErrorError *SchemaValidationErrorWrapper `protobuf:"bytes,202,opt,name=schema_validation_error_error,json=schemaValidationErrorError,proto3,oneof"`
}

func (*ErrorResponse_AppMessageArrayError) isErrorResponse_Error() {}

func (*ErrorResponse_SchemaValidationErrorError) isErrorResponse_Error() {}

type SchemaValidationError struct {
	state                   protoimpl.MessageState          `protogen:"open.v1"`
	Timestamp               string                          `protobuf:"bytes,201,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StatusCode              int32                           `protobuf:"varint,202,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Error                   string                          `protobuf:"bytes,203,opt,name=error,proto3" json:"error,omitempty"`
	Path                    string                          `protobuf:"bytes,204,opt,name=path,proto3" json:"path,omitempty"`
	ValidationErrorMessages []*SchemaValidationErrorMessage `protobuf:"bytes,205,rep,name=validation_error_messages,json=validationErrorMessages,proto3" json:"validation_error_messages,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SchemaValidationError) Reset() {
	*x = SchemaValidationError{}
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaValidationError) ProtoMessage() {}

func (x *SchemaValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaValidationError.ProtoReflect.Descriptor instead.
func (*SchemaValidationError) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP(), []int{4}
}

func (x *SchemaValidationError) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SchemaValidationError) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SchemaValidationError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SchemaValidationError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SchemaValidationError) GetValidationErrorMessages() []*SchemaValidationErrorMessage {
	if x != nil {
		return x.ValidationErrorMessages
	}
	return nil
}

type SchemaValidationErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,201,opt,name=location,proto3" json:"location,omitempty"`
	Message       string                 `protobuf:"bytes,202,opt,name=message,proto3" json:"message,omitempty"`
	AttributePath string                 `protobuf:"bytes,203,opt,name=attribute_path,json=attributePath,proto3" json:"attribute_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaValidationErrorMessage) Reset() {
	*x = SchemaValidationErrorMessage{}
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaValidationErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaValidationErrorMessage) ProtoMessage() {}

func (x *SchemaValidationErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaValidationErrorMessage.ProtoReflect.Descriptor instead.
func (*SchemaValidationErrorMessage) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP(), []int{5}
}

func (x *SchemaValidationErrorMessage) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SchemaValidationErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SchemaValidationErrorMessage) GetAttributePath() string {
	if x != nil {
		return x.AttributePath
	}
	return ""
}

var File_com_nutanix_dataprotection_v4_error_error_proto protoreflect.FileDescriptor

const file_com_nutanix_dataprotection_v4_error_error_proto_rawDesc = "" +
	"\n" +
	"/com/nutanix/dataprotection/v4/error/error.proto\x12#com.nutanix.dataprotection.v4.error\x1a)com/nutanix/common/v1/config/config.proto\"\x84\x03\n" +
	"\n" +
	"AppMessage\x12\x19\n" +
	"\amessage\x18\xc9\x01 \x01(\tR\amessage\x12a\n" +
	"\bseverity\x18\xca\x01 \x01(\x0e2D.com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverityR\bseverity\x12\x13\n" +
	"\x04code\x18\xcb\x01 \x01(\tR\x04code\x12\x17\n" +
	"\x06locale\x18\xcc\x01 \x01(\tR\x06locale\x12 \n" +
	"\verror_group\x18\xcd\x01 \x01(\tR\n" +
	"errorGroup\x12g\n" +
	"\rarguments_map\x18\xce\x01 \x03(\v2A.com.nutanix.dataprotection.v4.error.AppMessage.ArgumentsMapEntryR\fargumentsMap\x1a?\n" +
	"\x11ArgumentsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x16AppMessageArrayWrapper\x12F\n" +
	"\x05value\x18\xe8\a \x03(\v2/.com.nutanix.dataprotection.v4.error.AppMessageR\x05value\"q\n" +
	"\x1cSchemaValidationErrorWrapper\x12Q\n" +
	"\x05value\x18\xe8\a \x01(\v2:.com.nutanix.dataprotection.v4.error.SchemaValidationErrorR\x05value\"\x99\x02\n" +
	"\rErrorResponse\x12u\n" +
	"\x17app_message_array_error\x18\xc9\x01 \x01(\v2;.com.nutanix.dataprotection.v4.error.AppMessageArrayWrapperH\x00R\x14appMessageArrayError\x12\x87\x01\n" +
	"\x1dschema_validation_error_error\x18\xca\x01 \x01(\v2A.com.nutanix.dataprotection.v4.error.SchemaValidationErrorWrapperH\x00R\x1aschemaValidationErrorErrorB\a\n" +
	"\x05error\"\x84\x02\n" +
	"\x15SchemaValidationError\x12\x1d\n" +
	"\ttimestamp\x18\xc9\x01 \x01(\tR\ttimestamp\x12 \n" +
	"\vstatus_code\x18\xca\x01 \x01(\x05R\n" +
	"statusCode\x12\x15\n" +
	"\x05error\x18\xcb\x01 \x01(\tR\x05error\x12\x13\n" +
	"\x04path\x18\xcc\x01 \x01(\tR\x04path\x12~\n" +
	"\x19validation_error_messages\x18\xcd\x01 \x03(\v2A.com.nutanix.dataprotection.v4.error.SchemaValidationErrorMessageR\x17validationErrorMessages\"~\n" +
	"\x1cSchemaValidationErrorMessage\x12\x1b\n" +
	"\blocation\x18\xc9\x01 \x01(\tR\blocation\x12\x19\n" +
	"\amessage\x18\xca\x01 \x01(\tR\amessage\x12&\n" +
	"\x0eattribute_path\x18\xcb\x01 \x01(\tR\rattributePathBv\n" +
	"#com.nutanix.dataprotection.v4.errorP\x01ZMgithub.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/dataprotection/v4/errorb\x06proto3"

var (
	file_com_nutanix_dataprotection_v4_error_error_proto_rawDescOnce sync.Once
	file_com_nutanix_dataprotection_v4_error_error_proto_rawDescData []byte
)

func file_com_nutanix_dataprotection_v4_error_error_proto_rawDescGZIP() []byte {
	file_com_nutanix_dataprotection_v4_error_error_proto_rawDescOnce.Do(func() {
		file_com_nutanix_dataprotection_v4_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_error_error_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_error_error_proto_rawDesc)))
	})
	return file_com_nutanix_dataprotection_v4_error_error_proto_rawDescData
}

var file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_com_nutanix_dataprotection_v4_error_error_proto_goTypes = []any{
	(*AppMessage)(nil),                   // 0: com.nutanix.dataprotection.v4.error.AppMessage
	(*AppMessageArrayWrapper)(nil),       // 1: com.nutanix.dataprotection.v4.error.AppMessageArrayWrapper
	(*SchemaValidationErrorWrapper)(nil), // 2: com.nutanix.dataprotection.v4.error.SchemaValidationErrorWrapper
	(*ErrorResponse)(nil),                // 3: com.nutanix.dataprotection.v4.error.ErrorResponse
	(*SchemaValidationError)(nil),        // 4: com.nutanix.dataprotection.v4.error.SchemaValidationError
	(*SchemaValidationErrorMessage)(nil), // 5: com.nutanix.dataprotection.v4.error.SchemaValidationErrorMessage
	nil,                                  // 6: com.nutanix.dataprotection.v4.error.AppMessage.ArgumentsMapEntry
	(config.MessageSeverityMessage_MessageSeverity)(0), // 7: com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverity
}
var file_com_nutanix_dataprotection_v4_error_error_proto_depIdxs = []int32{
	7, // 0: com.nutanix.dataprotection.v4.error.AppMessage.severity:type_name -> com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverity
	6, // 1: com.nutanix.dataprotection.v4.error.AppMessage.arguments_map:type_name -> com.nutanix.dataprotection.v4.error.AppMessage.ArgumentsMapEntry
	0, // 2: com.nutanix.dataprotection.v4.error.AppMessageArrayWrapper.value:type_name -> com.nutanix.dataprotection.v4.error.AppMessage
	4, // 3: com.nutanix.dataprotection.v4.error.SchemaValidationErrorWrapper.value:type_name -> com.nutanix.dataprotection.v4.error.SchemaValidationError
	1, // 4: com.nutanix.dataprotection.v4.error.ErrorResponse.app_message_array_error:type_name -> com.nutanix.dataprotection.v4.error.AppMessageArrayWrapper
	2, // 5: com.nutanix.dataprotection.v4.error.ErrorResponse.schema_validation_error_error:type_name -> com.nutanix.dataprotection.v4.error.SchemaValidationErrorWrapper
	5, // 6: com.nutanix.dataprotection.v4.error.SchemaValidationError.validation_error_messages:type_name -> com.nutanix.dataprotection.v4.error.SchemaValidationErrorMessage
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_com_nutanix_dataprotection_v4_error_error_proto_init() }
func file_com_nutanix_dataprotection_v4_error_error_proto_init() {
	if File_com_nutanix_dataprotection_v4_error_error_proto != nil {
		return
	}
	file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes[3].OneofWrappers = []any{
		(*ErrorResponse_AppMessageArrayError)(nil),
		(*ErrorResponse_SchemaValidationErrorError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_error_error_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_error_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_nutanix_dataprotection_v4_error_error_proto_goTypes,
		DependencyIndexes: file_com_nutanix_dataprotection_v4_error_error_proto_depIdxs,
		MessageInfos:      file_com_nutanix_dataprotection_v4_error_error_proto_msgTypes,
	}.Build()
	File_com_nutanix_dataprotection_v4_error_error_proto = out.File
	file_com_nutanix_dataprotection_v4_error_error_proto_goTypes = nil
	file_com_nutanix_dataprotection_v4_error_error_proto_depIdxs = nil
}
