// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: com/nutanix/dataprotection/v4/api_version.proto

package v4

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiVersion struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MAJOR                 string                 `protobuf:"bytes,1,opt,name=MAJOR,proto3" json:"MAJOR,omitempty"`
	MINOR                 string                 `protobuf:"bytes,2,opt,name=MINOR,proto3" json:"MINOR,omitempty"`
	RELEASE_TYPE          string                 `protobuf:"bytes,3,opt,name=RELEASE_TYPE,json=RELEASETYPE,proto3" json:"RELEASE_TYPE,omitempty"`
	RELEASE_TYPE_REVISION string                 `protobuf:"bytes,4,opt,name=RELEASE_TYPE_REVISION,json=RELEASETYPEREVISION,proto3" json:"RELEASE_TYPE_REVISION,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ApiVersion) Reset() {
	*x = ApiVersion{}
	mi := &file_com_nutanix_dataprotection_v4_api_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiVersion) ProtoMessage() {}

func (x *ApiVersion) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_api_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiVersion.ProtoReflect.Descriptor instead.
func (*ApiVersion) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_api_version_proto_rawDescGZIP(), []int{0}
}

func (x *ApiVersion) GetMAJOR() string {
	if x != nil {
		return x.MAJOR
	}
	return ""
}

func (x *ApiVersion) GetMINOR() string {
	if x != nil {
		return x.MINOR
	}
	return ""
}

func (x *ApiVersion) GetRELEASE_TYPE() string {
	if x != nil {
		return x.RELEASE_TYPE
	}
	return ""
}

func (x *ApiVersion) GetRELEASE_TYPE_REVISION() string {
	if x != nil {
		return x.RELEASE_TYPE_REVISION
	}
	return ""
}

var file_com_nutanix_dataprotection_v4_api_version_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ApiVersion)(nil),
		Field:         2000,
		Name:          "com.nutanix.dataprotection.v4.ntnx_api_version",
		Tag:           "bytes,2000,opt,name=ntnx_api_version",
		Filename:      "com/nutanix/dataprotection/v4/api_version.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional com.nutanix.dataprotection.v4.ApiVersion ntnx_api_version = 2000;
	E_NtnxApiVersion = &file_com_nutanix_dataprotection_v4_api_version_proto_extTypes[0]
)

var File_com_nutanix_dataprotection_v4_api_version_proto protoreflect.FileDescriptor

const file_com_nutanix_dataprotection_v4_api_version_proto_rawDesc = "" +
	"\n" +
	"/com/nutanix/dataprotection/v4/api_version.proto\x12\x1dcom.nutanix.dataprotection.v4\x1a google/protobuf/descriptor.proto\"\x8f\x01\n" +
	"\n" +
	"ApiVersion\x12\x14\n" +
	"\x05MAJOR\x18\x01 \x01(\tR\x05MAJOR\x12\x14\n" +
	"\x05MINOR\x18\x02 \x01(\tR\x05MINOR\x12!\n" +
	"\fRELEASE_TYPE\x18\x03 \x01(\tR\vRELEASETYPE\x122\n" +
	"\x15RELEASE_TYPE_REVISION\x18\x04 \x01(\tR\x13RELEASETYPEREVISION:u\n" +
	"\x10ntnx_api_version\x12\x1f.google.protobuf.ServiceOptions\x18\xd0\x0f \x01(\v2).com.nutanix.dataprotection.v4.ApiVersionR\x0entnxApiVersionBj\n" +
	"\x1dcom.nutanix.dataprotection.v4P\x01ZGgithub.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/dataprotection/v4b\x06proto3"

var (
	file_com_nutanix_dataprotection_v4_api_version_proto_rawDescOnce sync.Once
	file_com_nutanix_dataprotection_v4_api_version_proto_rawDescData []byte
)

func file_com_nutanix_dataprotection_v4_api_version_proto_rawDescGZIP() []byte {
	file_com_nutanix_dataprotection_v4_api_version_proto_rawDescOnce.Do(func() {
		file_com_nutanix_dataprotection_v4_api_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_api_version_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_api_version_proto_rawDesc)))
	})
	return file_com_nutanix_dataprotection_v4_api_version_proto_rawDescData
}

var file_com_nutanix_dataprotection_v4_api_version_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_com_nutanix_dataprotection_v4_api_version_proto_goTypes = []any{
	(*ApiVersion)(nil),                  // 0: com.nutanix.dataprotection.v4.ApiVersion
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
}
var file_com_nutanix_dataprotection_v4_api_version_proto_depIdxs = []int32{
	1, // 0: com.nutanix.dataprotection.v4.ntnx_api_version:extendee -> google.protobuf.ServiceOptions
	0, // 1: com.nutanix.dataprotection.v4.ntnx_api_version:type_name -> com.nutanix.dataprotection.v4.ApiVersion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_nutanix_dataprotection_v4_api_version_proto_init() }
func file_com_nutanix_dataprotection_v4_api_version_proto_init() {
	if File_com_nutanix_dataprotection_v4_api_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_api_version_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_api_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_com_nutanix_dataprotection_v4_api_version_proto_goTypes,
		DependencyIndexes: file_com_nutanix_dataprotection_v4_api_version_proto_depIdxs,
		MessageInfos:      file_com_nutanix_dataprotection_v4_api_version_proto_msgTypes,
		ExtensionInfos:    file_com_nutanix_dataprotection_v4_api_version_proto_extTypes,
	}.Build()
	File_com_nutanix_dataprotection_v4_api_version_proto = out.File
	file_com_nutanix_dataprotection_v4_api_version_proto_goTypes = nil
	file_com_nutanix_dataprotection_v4_api_version_proto_depIdxs = nil
}
