//
// Generated file com/nutanix/common/v1/config/config.proto.
//
// Product version: 16.9.0-SNAPSHOT
//
// Part of the Nutanix Data Proetction gRPC APIs
//
// (c) 2024 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: com/nutanix/common/v1/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageSeverityMessage_MessageSeverity int32

const (
	MessageSeverityMessage_UNKNOWN  MessageSeverityMessage_MessageSeverity = 0
	MessageSeverityMessage_REDACTED MessageSeverityMessage_MessageSeverity = 1
	MessageSeverityMessage_INFO     MessageSeverityMessage_MessageSeverity = 1001
	MessageSeverityMessage_WARNING  MessageSeverityMessage_MessageSeverity = 1002
	MessageSeverityMessage_ERROR    MessageSeverityMessage_MessageSeverity = 1003
)

// Enum value maps for MessageSeverityMessage_MessageSeverity.
var (
	MessageSeverityMessage_MessageSeverity_name = map[int32]string{
		0:    "UNKNOWN",
		1:    "REDACTED",
		1001: "INFO",
		1002: "WARNING",
		1003: "ERROR",
	}
	MessageSeverityMessage_MessageSeverity_value = map[string]int32{
		"UNKNOWN":  0,
		"REDACTED": 1,
		"INFO":     1001,
		"WARNING":  1002,
		"ERROR":    1003,
	}
)

func (x MessageSeverityMessage_MessageSeverity) Enum() *MessageSeverityMessage_MessageSeverity {
	p := new(MessageSeverityMessage_MessageSeverity)
	*p = x
	return p
}

func (x MessageSeverityMessage_MessageSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageSeverityMessage_MessageSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_com_nutanix_common_v1_config_config_proto_enumTypes[0].Descriptor()
}

func (MessageSeverityMessage_MessageSeverity) Type() protoreflect.EnumType {
	return &file_com_nutanix_common_v1_config_config_proto_enumTypes[0]
}

func (x MessageSeverityMessage_MessageSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageSeverityMessage_MessageSeverity.Descriptor instead.
func (MessageSeverityMessage_MessageSeverity) EnumDescriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{11, 0}
}

type Flag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1001,opt,name=name,proto3" json:"name,omitempty"`
	Value         bool                   `protobuf:"varint,1002,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type IPAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ipv4          *IPv4Address           `protobuf:"bytes,1001,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          *IPv6Address           `protobuf:"bytes,1002,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *IPAddress) GetIpv4() *IPv4Address {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *IPAddress) GetIpv6() *IPv6Address {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

type IPv4Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1001,opt,name=value,proto3" json:"value,omitempty"`
	PrefixLength  int32                  `protobuf:"varint,1002,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv4Address) Reset() {
	*x = IPv4Address{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv4Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4Address) ProtoMessage() {}

func (x *IPv4Address) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4Address.ProtoReflect.Descriptor instead.
func (*IPv4Address) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *IPv4Address) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IPv4Address) GetPrefixLength() int32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

type IPv6Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1001,opt,name=value,proto3" json:"value,omitempty"`
	PrefixLength  int32                  `protobuf:"varint,1002,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv6Address) Reset() {
	*x = IPv6Address{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv6Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Address) ProtoMessage() {}

func (x *IPv6Address) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Address.ProtoReflect.Descriptor instead.
func (*IPv6Address) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *IPv6Address) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *IPv6Address) GetPrefixLength() int32 {
	if x != nil {
		return x.PrefixLength
	}
	return 0
}

type StringWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1000,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringWrapper) Reset() {
	*x = StringWrapper{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringWrapper) ProtoMessage() {}

func (x *StringWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringWrapper.ProtoReflect.Descriptor instead.
func (*StringWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{4}
}

func (x *StringWrapper) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IntegerWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1000,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegerWrapper) Reset() {
	*x = IntegerWrapper{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegerWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegerWrapper) ProtoMessage() {}

func (x *IntegerWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegerWrapper.ProtoReflect.Descriptor instead.
func (*IntegerWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{5}
}

func (x *IntegerWrapper) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BooleanWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1000,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanWrapper) Reset() {
	*x = BooleanWrapper{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanWrapper) ProtoMessage() {}

func (x *BooleanWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanWrapper.ProtoReflect.Descriptor instead.
func (*BooleanWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{6}
}

func (x *BooleanWrapper) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type StringArrayWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []string               `protobuf:"bytes,1000,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringArrayWrapper) Reset() {
	*x = StringArrayWrapper{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArrayWrapper) ProtoMessage() {}

func (x *StringArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArrayWrapper.ProtoReflect.Descriptor instead.
func (*StringArrayWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{7}
}

func (x *StringArrayWrapper) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type StringMapWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]string      `protobuf:"bytes,1000,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMapWrapper) Reset() {
	*x = StringMapWrapper{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMapWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMapWrapper) ProtoMessage() {}

func (x *StringMapWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMapWrapper.ProtoReflect.Descriptor instead.
func (*StringMapWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{8}
}

func (x *StringMapWrapper) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

type KVPair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map describing a set of keys and their corresponding values.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*KVPair_StringValue
	//	*KVPair_IntegerValue
	//	*KVPair_BooleanValue
	//	*KVPair_StringArrayValue
	//	*KVPair_StringMapValue
	Value         isKVPair_Value `protobuf_oneof:"value"`
	Name          string         `protobuf:"bytes,1001,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{9}
}

func (x *KVPair) GetValue() isKVPair_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KVPair) GetStringValue() *StringWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_StringValue); ok {
			return x.StringValue
		}
	}
	return nil
}

func (x *KVPair) GetIntegerValue() *IntegerWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_IntegerValue); ok {
			return x.IntegerValue
		}
	}
	return nil
}

func (x *KVPair) GetBooleanValue() *BooleanWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return nil
}

func (x *KVPair) GetStringArrayValue() *StringArrayWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_StringArrayValue); ok {
			return x.StringArrayValue
		}
	}
	return nil
}

func (x *KVPair) GetStringMapValue() *StringMapWrapper {
	if x != nil {
		if x, ok := x.Value.(*KVPair_StringMapValue); ok {
			return x.StringMapValue
		}
	}
	return nil
}

func (x *KVPair) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type isKVPair_Value interface {
	isKVPair_Value()
}

type KVPair_StringValue struct {
	StringValue *StringWrapper `protobuf:"bytes,1002,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type KVPair_IntegerValue struct {
	IntegerValue *IntegerWrapper `protobuf:"bytes,1003,opt,name=integer_value,json=integerValue,proto3,oneof"`
}

type KVPair_BooleanValue struct {
	BooleanValue *BooleanWrapper `protobuf:"bytes,1004,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type KVPair_StringArrayValue struct {
	StringArrayValue *StringArrayWrapper `protobuf:"bytes,1005,opt,name=string_array_value,json=stringArrayValue,proto3,oneof"`
}

type KVPair_StringMapValue struct {
	StringMapValue *StringMapWrapper `protobuf:"bytes,1006,opt,name=string_map_value,json=stringMapValue,proto3,oneof"`
}

func (*KVPair_StringValue) isKVPair_Value() {}

func (*KVPair_IntegerValue) isKVPair_Value() {}

func (*KVPair_BooleanValue) isKVPair_Value() {}

func (*KVPair_StringArrayValue) isKVPair_Value() {}

func (*KVPair_StringMapValue) isKVPair_Value() {}

type Message struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Code          string                                 `protobuf:"bytes,1001,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                                 `protobuf:"bytes,1002,opt,name=message,proto3" json:"message,omitempty"`
	Locale        string                                 `protobuf:"bytes,1003,opt,name=locale,proto3" json:"locale,omitempty"`
	Severity      MessageSeverityMessage_MessageSeverity `protobuf:"varint,1004,opt,name=severity,proto3,enum=com.nutanix.common.v1.config.MessageSeverityMessage_MessageSeverity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Message) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Message) GetSeverity() MessageSeverityMessage_MessageSeverity {
	if x != nil {
		return x.Severity
	}
	return MessageSeverityMessage_UNKNOWN
}

// The message severity.
type MessageSeverityMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSeverityMessage) Reset() {
	*x = MessageSeverityMessage{}
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSeverityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSeverityMessage) ProtoMessage() {}

func (x *MessageSeverityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_config_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSeverityMessage.ProtoReflect.Descriptor instead.
func (*MessageSeverityMessage) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_config_config_proto_rawDescGZIP(), []int{11}
}

var File_com_nutanix_common_v1_config_config_proto protoreflect.FileDescriptor

const file_com_nutanix_common_v1_config_config_proto_rawDesc = "" +
	"\n" +
	")com/nutanix/common/v1/config/config.proto\x12\x1ccom.nutanix.common.v1.config\"2\n" +
	"\x04Flag\x12\x13\n" +
	"\x04name\x18\xe9\a \x01(\tR\x04name\x12\x15\n" +
	"\x05value\x18\xea\a \x01(\bR\x05value\"\x8b\x01\n" +
	"\tIPAddress\x12>\n" +
	"\x04ipv4\x18\xe9\a \x01(\v2).com.nutanix.common.v1.config.IPv4AddressR\x04ipv4\x12>\n" +
	"\x04ipv6\x18\xea\a \x01(\v2).com.nutanix.common.v1.config.IPv6AddressR\x04ipv6\"J\n" +
	"\vIPv4Address\x12\x15\n" +
	"\x05value\x18\xe9\a \x01(\tR\x05value\x12$\n" +
	"\rprefix_length\x18\xea\a \x01(\x05R\fprefixLength\"J\n" +
	"\vIPv6Address\x12\x15\n" +
	"\x05value\x18\xe9\a \x01(\tR\x05value\x12$\n" +
	"\rprefix_length\x18\xea\a \x01(\x05R\fprefixLength\"&\n" +
	"\rStringWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x01(\tR\x05value\"'\n" +
	"\x0eIntegerWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x01(\x05R\x05value\"'\n" +
	"\x0eBooleanWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x01(\bR\x05value\"+\n" +
	"\x12StringArrayWrapper\x12\x15\n" +
	"\x05value\x18\xe8\a \x03(\tR\x05value\"\x9e\x01\n" +
	"\x10StringMapWrapper\x12P\n" +
	"\x05value\x18\xe8\a \x03(\v29.com.nutanix.common.v1.config.StringMapWrapper.ValueEntryR\x05value\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x03\n" +
	"\x06KVPair\x12Q\n" +
	"\fstring_value\x18\xea\a \x01(\v2+.com.nutanix.common.v1.config.StringWrapperH\x00R\vstringValue\x12T\n" +
	"\rinteger_value\x18\xeb\a \x01(\v2,.com.nutanix.common.v1.config.IntegerWrapperH\x00R\fintegerValue\x12T\n" +
	"\rboolean_value\x18\xec\a \x01(\v2,.com.nutanix.common.v1.config.BooleanWrapperH\x00R\fbooleanValue\x12a\n" +
	"\x12string_array_value\x18\xed\a \x01(\v20.com.nutanix.common.v1.config.StringArrayWrapperH\x00R\x10stringArrayValue\x12[\n" +
	"\x10string_map_value\x18\xee\a \x01(\v2..com.nutanix.common.v1.config.StringMapWrapperH\x00R\x0estringMapValue\x12\x13\n" +
	"\x04name\x18\xe9\a \x01(\tR\x04nameB\a\n" +
	"\x05value\"\xb5\x01\n" +
	"\aMessage\x12\x13\n" +
	"\x04code\x18\xe9\a \x01(\tR\x04code\x12\x19\n" +
	"\amessage\x18\xea\a \x01(\tR\amessage\x12\x17\n" +
	"\x06locale\x18\xeb\a \x01(\tR\x06locale\x12a\n" +
	"\bseverity\x18\xec\a \x01(\x0e2D.com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverityR\bseverity\"k\n" +
	"\x16MessageSeverityMessage\"Q\n" +
	"\x0fMessageSeverity\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREDACTED\x10\x01\x12\t\n" +
	"\x04INFO\x10\xe9\a\x12\f\n" +
	"\aWARNING\x10\xea\a\x12\n" +
	"\n" +
	"\x05ERROR\x10\xeb\aBh\n" +
	"\x1ccom.nutanix.common.v1.configP\x01ZFgithub.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/common/v1/configb\x06proto3"

var (
	file_com_nutanix_common_v1_config_config_proto_rawDescOnce sync.Once
	file_com_nutanix_common_v1_config_config_proto_rawDescData []byte
)

func file_com_nutanix_common_v1_config_config_proto_rawDescGZIP() []byte {
	file_com_nutanix_common_v1_config_config_proto_rawDescOnce.Do(func() {
		file_com_nutanix_common_v1_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_nutanix_common_v1_config_config_proto_rawDesc), len(file_com_nutanix_common_v1_config_config_proto_rawDesc)))
	})
	return file_com_nutanix_common_v1_config_config_proto_rawDescData
}

var file_com_nutanix_common_v1_config_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_nutanix_common_v1_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_com_nutanix_common_v1_config_config_proto_goTypes = []any{
	(MessageSeverityMessage_MessageSeverity)(0), // 0: com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverity
	(*Flag)(nil),                   // 1: com.nutanix.common.v1.config.Flag
	(*IPAddress)(nil),              // 2: com.nutanix.common.v1.config.IPAddress
	(*IPv4Address)(nil),            // 3: com.nutanix.common.v1.config.IPv4Address
	(*IPv6Address)(nil),            // 4: com.nutanix.common.v1.config.IPv6Address
	(*StringWrapper)(nil),          // 5: com.nutanix.common.v1.config.StringWrapper
	(*IntegerWrapper)(nil),         // 6: com.nutanix.common.v1.config.IntegerWrapper
	(*BooleanWrapper)(nil),         // 7: com.nutanix.common.v1.config.BooleanWrapper
	(*StringArrayWrapper)(nil),     // 8: com.nutanix.common.v1.config.StringArrayWrapper
	(*StringMapWrapper)(nil),       // 9: com.nutanix.common.v1.config.StringMapWrapper
	(*KVPair)(nil),                 // 10: com.nutanix.common.v1.config.KVPair
	(*Message)(nil),                // 11: com.nutanix.common.v1.config.Message
	(*MessageSeverityMessage)(nil), // 12: com.nutanix.common.v1.config.MessageSeverityMessage
	nil,                            // 13: com.nutanix.common.v1.config.StringMapWrapper.ValueEntry
}
var file_com_nutanix_common_v1_config_config_proto_depIdxs = []int32{
	3,  // 0: com.nutanix.common.v1.config.IPAddress.ipv4:type_name -> com.nutanix.common.v1.config.IPv4Address
	4,  // 1: com.nutanix.common.v1.config.IPAddress.ipv6:type_name -> com.nutanix.common.v1.config.IPv6Address
	13, // 2: com.nutanix.common.v1.config.StringMapWrapper.value:type_name -> com.nutanix.common.v1.config.StringMapWrapper.ValueEntry
	5,  // 3: com.nutanix.common.v1.config.KVPair.string_value:type_name -> com.nutanix.common.v1.config.StringWrapper
	6,  // 4: com.nutanix.common.v1.config.KVPair.integer_value:type_name -> com.nutanix.common.v1.config.IntegerWrapper
	7,  // 5: com.nutanix.common.v1.config.KVPair.boolean_value:type_name -> com.nutanix.common.v1.config.BooleanWrapper
	8,  // 6: com.nutanix.common.v1.config.KVPair.string_array_value:type_name -> com.nutanix.common.v1.config.StringArrayWrapper
	9,  // 7: com.nutanix.common.v1.config.KVPair.string_map_value:type_name -> com.nutanix.common.v1.config.StringMapWrapper
	0,  // 8: com.nutanix.common.v1.config.Message.severity:type_name -> com.nutanix.common.v1.config.MessageSeverityMessage.MessageSeverity
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_com_nutanix_common_v1_config_config_proto_init() }
func file_com_nutanix_common_v1_config_config_proto_init() {
	if File_com_nutanix_common_v1_config_config_proto != nil {
		return
	}
	file_com_nutanix_common_v1_config_config_proto_msgTypes[9].OneofWrappers = []any{
		(*KVPair_StringValue)(nil),
		(*KVPair_IntegerValue)(nil),
		(*KVPair_BooleanValue)(nil),
		(*KVPair_StringArrayValue)(nil),
		(*KVPair_StringMapValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_nutanix_common_v1_config_config_proto_rawDesc), len(file_com_nutanix_common_v1_config_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_nutanix_common_v1_config_config_proto_goTypes,
		DependencyIndexes: file_com_nutanix_common_v1_config_config_proto_depIdxs,
		EnumInfos:         file_com_nutanix_common_v1_config_config_proto_enumTypes,
		MessageInfos:      file_com_nutanix_common_v1_config_config_proto_msgTypes,
	}.Build()
	File_com_nutanix_common_v1_config_config_proto = out.File
	file_com_nutanix_common_v1_config_config_proto_goTypes = nil
	file_com_nutanix_common_v1_config_config_proto_depIdxs = nil
}
