//
// Generated file com/nutanix/dataprotection/v4/content/content.proto.
//
// Product version: 16.9.0-SNAPSHOT
//
// Part of the Nutanix Data Proetction gRPC APIs
//
// (c) 2024 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: com/nutanix/dataprotection/v4/content/content.proto

package content

import (
	config "github.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/common/v1/config"
	response "github.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/common/v1/response"
	error1 "github.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/dataprotection/v4/error"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionTypeMessage_RegionType int32

const (
	RegionTypeMessage_UNKNOWN  RegionTypeMessage_RegionType = 0
	RegionTypeMessage_REDACTED RegionTypeMessage_RegionType = 1
	RegionTypeMessage_ZEROED   RegionTypeMessage_RegionType = 2001
	RegionTypeMessage_REGULAR  RegionTypeMessage_RegionType = 2002
)

// Enum value maps for RegionTypeMessage_RegionType.
var (
	RegionTypeMessage_RegionType_name = map[int32]string{
		0:    "UNKNOWN",
		1:    "REDACTED",
		2001: "ZEROED",
		2002: "REGULAR",
	}
	RegionTypeMessage_RegionType_value = map[string]int32{
		"UNKNOWN":  0,
		"REDACTED": 1,
		"ZEROED":   2001,
		"REGULAR":  2002,
	}
)

func (x RegionTypeMessage_RegionType) Enum() *RegionTypeMessage_RegionType {
	p := new(RegionTypeMessage_RegionType)
	*p = x
	return p
}

func (x RegionTypeMessage_RegionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionTypeMessage_RegionType) Descriptor() protoreflect.EnumDescriptor {
	return file_com_nutanix_dataprotection_v4_content_content_proto_enumTypes[0].Descriptor()
}

func (RegionTypeMessage_RegionType) Type() protoreflect.EnumType {
	return &file_com_nutanix_dataprotection_v4_content_content_proto_enumTypes[0]
}

func (x RegionTypeMessage_RegionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionTypeMessage_RegionType.Descriptor instead.
func (RegionTypeMessage_RegionType) EnumDescriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{6, 0}
}

type BaseRecoveryPointSpec struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	ReferenceRecoveryPointExtId     string                 `protobuf:"bytes,2001,opt,name=reference_recovery_point_ext_id,json=referenceRecoveryPointExtId,proto3" json:"reference_recovery_point_ext_id,omitempty"`
	ReferenceDiskRecoveryPointExtId string                 `protobuf:"bytes,2002,opt,name=reference_disk_recovery_point_ext_id,json=referenceDiskRecoveryPointExtId,proto3" json:"reference_disk_recovery_point_ext_id,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *BaseRecoveryPointSpec) Reset() {
	*x = BaseRecoveryPointSpec{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRecoveryPointSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRecoveryPointSpec) ProtoMessage() {}

func (x *BaseRecoveryPointSpec) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRecoveryPointSpec.ProtoReflect.Descriptor instead.
func (*BaseRecoveryPointSpec) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *BaseRecoveryPointSpec) GetReferenceRecoveryPointExtId() string {
	if x != nil {
		return x.ReferenceRecoveryPointExtId
	}
	return ""
}

func (x *BaseRecoveryPointSpec) GetReferenceDiskRecoveryPointExtId() string {
	if x != nil {
		return x.ReferenceDiskRecoveryPointExtId
	}
	return ""
}

type ChangedRegion struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Offset        int64                        `protobuf:"varint,2001,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                        `protobuf:"varint,2002,opt,name=length,proto3" json:"length,omitempty"`
	RegionType    RegionTypeMessage_RegionType `protobuf:"varint,2003,opt,name=region_type,json=regionType,proto3,enum=com.nutanix.dataprotection.v4.content.RegionTypeMessage_RegionType" json:"region_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedRegion) Reset() {
	*x = ChangedRegion{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedRegion) ProtoMessage() {}

func (x *ChangedRegion) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedRegion.ProtoReflect.Descriptor instead.
func (*ChangedRegion) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *ChangedRegion) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ChangedRegion) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ChangedRegion) GetRegionType() RegionTypeMessage_RegionType {
	if x != nil {
		return x.RegionType
	}
	return RegionTypeMessage_UNKNOWN
}

type ChangedRegionArrayWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*ChangedRegion       `protobuf:"bytes,1000,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedRegionArrayWrapper) Reset() {
	*x = ChangedRegionArrayWrapper{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedRegionArrayWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedRegionArrayWrapper) ProtoMessage() {}

func (x *ChangedRegionArrayWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedRegionArrayWrapper.ProtoReflect.Descriptor instead.
func (*ChangedRegionArrayWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *ChangedRegionArrayWrapper) GetValue() []*ChangedRegion {
	if x != nil {
		return x.Value
	}
	return nil
}

type ErrorResponseWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *error1.ErrorResponse  `protobuf:"bytes,1000,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponseWrapper) Reset() {
	*x = ErrorResponseWrapper{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponseWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponseWrapper) ProtoMessage() {}

func (x *ErrorResponseWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponseWrapper.ProtoReflect.Descriptor instead.
func (*ErrorResponseWrapper) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponseWrapper) GetValue() *error1.ErrorResponse {
	if x != nil {
		return x.Value
	}
	return nil
}

type ChangedRegionsModel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// REST response for all response codes in API path /dataprotection/v4.0.a1/content/recovery-points/{recoveryPointExtId}/volume-group-recovery-points/{volumeGroupRecoveryPointExtId}/disk-recovery-points/{extId}/$actions/compute-changed-regions Post operation
	//
	// Types that are valid to be assigned to Data:
	//
	//	*ChangedRegionsModel_ChangedRegionArrayData
	//	*ChangedRegionsModel_ErrorResponseData
	Data          isChangedRegionsModel_Data    `protobuf_oneof:"data"`
	Metadata      *response.ApiResponseMetadata `protobuf:"bytes,1001,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedRegionsModel) Reset() {
	*x = ChangedRegionsModel{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedRegionsModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedRegionsModel) ProtoMessage() {}

func (x *ChangedRegionsModel) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedRegionsModel.ProtoReflect.Descriptor instead.
func (*ChangedRegionsModel) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *ChangedRegionsModel) GetData() isChangedRegionsModel_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChangedRegionsModel) GetChangedRegionArrayData() *ChangedRegionArrayWrapper {
	if x != nil {
		if x, ok := x.Data.(*ChangedRegionsModel_ChangedRegionArrayData); ok {
			return x.ChangedRegionArrayData
		}
	}
	return nil
}

func (x *ChangedRegionsModel) GetErrorResponseData() *ErrorResponseWrapper {
	if x != nil {
		if x, ok := x.Data.(*ChangedRegionsModel_ErrorResponseData); ok {
			return x.ErrorResponseData
		}
	}
	return nil
}

func (x *ChangedRegionsModel) GetMetadata() *response.ApiResponseMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isChangedRegionsModel_Data interface {
	isChangedRegionsModel_Data()
}

type ChangedRegionsModel_ChangedRegionArrayData struct {
	ChangedRegionArrayData *ChangedRegionArrayWrapper `protobuf:"bytes,2003,opt,name=changed_region_array_data,json=changedRegionArrayData,proto3,oneof"`
}

type ChangedRegionsModel_ErrorResponseData struct {
	ErrorResponseData *ErrorResponseWrapper `protobuf:"bytes,400,opt,name=error_response_data,json=errorResponseData,proto3,oneof"`
}

func (*ChangedRegionsModel_ChangedRegionArrayData) isChangedRegionsModel_Data() {}

func (*ChangedRegionsModel_ErrorResponseData) isChangedRegionsModel_Data() {}

type ClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   string                 `protobuf:"bytes,2001,opt,name=certificate,proto3" json:"certificate,omitempty"`
	RedirectIp    *config.IPAddress      `protobuf:"bytes,2002,opt,name=redirect_ip,json=redirectIp,proto3" json:"redirect_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterInfo) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *ClusterInfo) GetRedirectIp() *config.IPAddress {
	if x != nil {
		return x.RedirectIp
	}
	return nil
}

// The type of the region.
type RegionTypeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionTypeMessage) Reset() {
	*x = RegionTypeMessage{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionTypeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionTypeMessage) ProtoMessage() {}

func (x *RegionTypeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionTypeMessage.ProtoReflect.Descriptor instead.
func (*RegionTypeMessage) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{6}
}

type VmDiskRecoveryPointClusterDiscoverSpec struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Base                          *BaseRecoveryPointSpec `protobuf:"bytes,2004,opt,name=base,proto3" json:"base,omitempty"`
	ReferenceVmRecoveryPointExtId string                 `protobuf:"bytes,2005,opt,name=reference_vm_recovery_point_ext_id,json=referenceVmRecoveryPointExtId,proto3" json:"reference_vm_recovery_point_ext_id,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *VmDiskRecoveryPointClusterDiscoverSpec) Reset() {
	*x = VmDiskRecoveryPointClusterDiscoverSpec{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmDiskRecoveryPointClusterDiscoverSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmDiskRecoveryPointClusterDiscoverSpec) ProtoMessage() {}

func (x *VmDiskRecoveryPointClusterDiscoverSpec) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmDiskRecoveryPointClusterDiscoverSpec.ProtoReflect.Descriptor instead.
func (*VmDiskRecoveryPointClusterDiscoverSpec) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{7}
}

func (x *VmDiskRecoveryPointClusterDiscoverSpec) GetBase() *BaseRecoveryPointSpec {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *VmDiskRecoveryPointClusterDiscoverSpec) GetReferenceVmRecoveryPointExtId() string {
	if x != nil {
		return x.ReferenceVmRecoveryPointExtId
	}
	return ""
}

type VmRecoveryPointChangedRegionsComputeSpec struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Base          *VmDiskRecoveryPointClusterDiscoverSpec `protobuf:"bytes,2009,opt,name=base,proto3" json:"base,omitempty"`
	Offset        int64                                   `protobuf:"varint,2010,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                                   `protobuf:"varint,2011,opt,name=length,proto3" json:"length,omitempty"`
	BlockSize     int64                                   `protobuf:"varint,2012,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VmRecoveryPointChangedRegionsComputeSpec) Reset() {
	*x = VmRecoveryPointChangedRegionsComputeSpec{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VmRecoveryPointChangedRegionsComputeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VmRecoveryPointChangedRegionsComputeSpec) ProtoMessage() {}

func (x *VmRecoveryPointChangedRegionsComputeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VmRecoveryPointChangedRegionsComputeSpec.ProtoReflect.Descriptor instead.
func (*VmRecoveryPointChangedRegionsComputeSpec) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{8}
}

func (x *VmRecoveryPointChangedRegionsComputeSpec) GetBase() *VmDiskRecoveryPointClusterDiscoverSpec {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *VmRecoveryPointChangedRegionsComputeSpec) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VmRecoveryPointChangedRegionsComputeSpec) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *VmRecoveryPointChangedRegionsComputeSpec) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type VolumeGroupDiskRecoveryPointClusterDiscoverSpec struct {
	state                                  protoimpl.MessageState `protogen:"open.v1"`
	Base                                   *BaseRecoveryPointSpec `protobuf:"bytes,2004,opt,name=base,proto3" json:"base,omitempty"`
	ReferenceVolumeGroupRecoveryPointExtId string                 `protobuf:"bytes,2005,opt,name=reference_volume_group_recovery_point_ext_id,json=referenceVolumeGroupRecoveryPointExtId,proto3" json:"reference_volume_group_recovery_point_ext_id,omitempty"`
	unknownFields                          protoimpl.UnknownFields
	sizeCache                              protoimpl.SizeCache
}

func (x *VolumeGroupDiskRecoveryPointClusterDiscoverSpec) Reset() {
	*x = VolumeGroupDiskRecoveryPointClusterDiscoverSpec{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroupDiskRecoveryPointClusterDiscoverSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroupDiskRecoveryPointClusterDiscoverSpec) ProtoMessage() {}

func (x *VolumeGroupDiskRecoveryPointClusterDiscoverSpec) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroupDiskRecoveryPointClusterDiscoverSpec.ProtoReflect.Descriptor instead.
func (*VolumeGroupDiskRecoveryPointClusterDiscoverSpec) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{9}
}

func (x *VolumeGroupDiskRecoveryPointClusterDiscoverSpec) GetBase() *BaseRecoveryPointSpec {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *VolumeGroupDiskRecoveryPointClusterDiscoverSpec) GetReferenceVolumeGroupRecoveryPointExtId() string {
	if x != nil {
		return x.ReferenceVolumeGroupRecoveryPointExtId
	}
	return ""
}

type VolumeGroupRecoveryPointChangedRegionsComputeSpec struct {
	state         protoimpl.MessageState                           `protogen:"open.v1"`
	Base          *VolumeGroupDiskRecoveryPointClusterDiscoverSpec `protobuf:"bytes,2009,opt,name=base,proto3" json:"base,omitempty"`
	Offset        int64                                            `protobuf:"varint,2010,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                                            `protobuf:"varint,2011,opt,name=length,proto3" json:"length,omitempty"`
	BlockSize     int64                                            `protobuf:"varint,2012,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) Reset() {
	*x = VolumeGroupRecoveryPointChangedRegionsComputeSpec{}
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroupRecoveryPointChangedRegionsComputeSpec) ProtoMessage() {}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroupRecoveryPointChangedRegionsComputeSpec.ProtoReflect.Descriptor instead.
func (*VolumeGroupRecoveryPointChangedRegionsComputeSpec) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP(), []int{10}
}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) GetBase() *VolumeGroupDiskRecoveryPointClusterDiscoverSpec {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *VolumeGroupRecoveryPointChangedRegionsComputeSpec) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

var File_com_nutanix_dataprotection_v4_content_content_proto protoreflect.FileDescriptor

const file_com_nutanix_dataprotection_v4_content_content_proto_rawDesc = "" +
	"\n" +
	"3com/nutanix/dataprotection/v4/content/content.proto\x12%com.nutanix.dataprotection.v4.content\x1a/com/nutanix/dataprotection/v4/error/error.proto\x1a-com/nutanix/common/v1/response/response.proto\x1a)com/nutanix/common/v1/config/config.proto\"\xae\x01\n" +
	"\x15BaseRecoveryPointSpec\x12E\n" +
	"\x1freference_recovery_point_ext_id\x18\xd1\x0f \x01(\tR\x1breferenceRecoveryPointExtId\x12N\n" +
	"$reference_disk_recovery_point_ext_id\x18\xd2\x0f \x01(\tR\x1freferenceDiskRecoveryPointExtId\"\xa8\x01\n" +
	"\rChangedRegion\x12\x17\n" +
	"\x06offset\x18\xd1\x0f \x01(\x03R\x06offset\x12\x17\n" +
	"\x06length\x18\xd2\x0f \x01(\x03R\x06length\x12e\n" +
	"\vregion_type\x18\xd3\x0f \x01(\x0e2C.com.nutanix.dataprotection.v4.content.RegionTypeMessage.RegionTypeR\n" +
	"regionType\"h\n" +
	"\x19ChangedRegionArrayWrapper\x12K\n" +
	"\x05value\x18\xe8\a \x03(\v24.com.nutanix.dataprotection.v4.content.ChangedRegionR\x05value\"a\n" +
	"\x14ErrorResponseWrapper\x12I\n" +
	"\x05value\x18\xe8\a \x01(\v22.com.nutanix.dataprotection.v4.error.ErrorResponseR\x05value\"\xdf\x02\n" +
	"\x13ChangedRegionsModel\x12~\n" +
	"\x19changed_region_array_data\x18\xd3\x0f \x01(\v2@.com.nutanix.dataprotection.v4.content.ChangedRegionArrayWrapperH\x00R\x16changedRegionArrayData\x12n\n" +
	"\x13error_response_data\x18\x90\x03 \x01(\v2;.com.nutanix.dataprotection.v4.content.ErrorResponseWrapperH\x00R\x11errorResponseData\x12P\n" +
	"\bmetadata\x18\xe9\a \x01(\v23.com.nutanix.common.v1.response.ApiResponseMetadataR\bmetadataB\x06\n" +
	"\x04data\"{\n" +
	"\vClusterInfo\x12!\n" +
	"\vcertificate\x18\xd1\x0f \x01(\tR\vcertificate\x12I\n" +
	"\vredirect_ip\x18\xd2\x0f \x01(\v2'.com.nutanix.common.v1.config.IPAddressR\n" +
	"redirectIp\"W\n" +
	"\x11RegionTypeMessage\"B\n" +
	"\n" +
	"RegionType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREDACTED\x10\x01\x12\v\n" +
	"\x06ZEROED\x10\xd1\x0f\x12\f\n" +
	"\aREGULAR\x10\xd2\x0f\"\xc7\x01\n" +
	"&VmDiskRecoveryPointClusterDiscoverSpec\x12Q\n" +
	"\x04base\x18\xd4\x0f \x01(\v2<.com.nutanix.dataprotection.v4.content.BaseRecoveryPointSpecR\x04base\x12J\n" +
	"\"reference_vm_recovery_point_ext_id\x18\xd5\x0f \x01(\tR\x1dreferenceVmRecoveryPointExtId\"\xe0\x01\n" +
	"(VmRecoveryPointChangedRegionsComputeSpec\x12b\n" +
	"\x04base\x18\xd9\x0f \x01(\v2M.com.nutanix.dataprotection.v4.content.VmDiskRecoveryPointClusterDiscoverSpecR\x04base\x12\x17\n" +
	"\x06offset\x18\xda\x0f \x01(\x03R\x06offset\x12\x17\n" +
	"\x06length\x18\xdb\x0f \x01(\x03R\x06length\x12\x1e\n" +
	"\n" +
	"block_size\x18\xdc\x0f \x01(\x03R\tblockSize\"\xe3\x01\n" +
	"/VolumeGroupDiskRecoveryPointClusterDiscoverSpec\x12Q\n" +
	"\x04base\x18\xd4\x0f \x01(\v2<.com.nutanix.dataprotection.v4.content.BaseRecoveryPointSpecR\x04base\x12]\n" +
	",reference_volume_group_recovery_point_ext_id\x18\xd5\x0f \x01(\tR&referenceVolumeGroupRecoveryPointExtId\"\xf2\x01\n" +
	"1VolumeGroupRecoveryPointChangedRegionsComputeSpec\x12k\n" +
	"\x04base\x18\xd9\x0f \x01(\v2V.com.nutanix.dataprotection.v4.content.VolumeGroupDiskRecoveryPointClusterDiscoverSpecR\x04base\x12\x17\n" +
	"\x06offset\x18\xda\x0f \x01(\x03R\x06offset\x12\x17\n" +
	"\x06length\x18\xdb\x0f \x01(\x03R\x06length\x12\x1e\n" +
	"\n" +
	"block_size\x18\xdc\x0f \x01(\x03R\tblockSizeBz\n" +
	"%com.nutanix.dataprotection.v4.contentP\x01ZOgithub.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/dataprotection/v4/contentb\x06proto3"

var (
	file_com_nutanix_dataprotection_v4_content_content_proto_rawDescOnce sync.Once
	file_com_nutanix_dataprotection_v4_content_content_proto_rawDescData []byte
)

func file_com_nutanix_dataprotection_v4_content_content_proto_rawDescGZIP() []byte {
	file_com_nutanix_dataprotection_v4_content_content_proto_rawDescOnce.Do(func() {
		file_com_nutanix_dataprotection_v4_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_content_content_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_content_content_proto_rawDesc)))
	})
	return file_com_nutanix_dataprotection_v4_content_content_proto_rawDescData
}

var file_com_nutanix_dataprotection_v4_content_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_com_nutanix_dataprotection_v4_content_content_proto_goTypes = []any{
	(RegionTypeMessage_RegionType)(0),                         // 0: com.nutanix.dataprotection.v4.content.RegionTypeMessage.RegionType
	(*BaseRecoveryPointSpec)(nil),                             // 1: com.nutanix.dataprotection.v4.content.BaseRecoveryPointSpec
	(*ChangedRegion)(nil),                                     // 2: com.nutanix.dataprotection.v4.content.ChangedRegion
	(*ChangedRegionArrayWrapper)(nil),                         // 3: com.nutanix.dataprotection.v4.content.ChangedRegionArrayWrapper
	(*ErrorResponseWrapper)(nil),                              // 4: com.nutanix.dataprotection.v4.content.ErrorResponseWrapper
	(*ChangedRegionsModel)(nil),                               // 5: com.nutanix.dataprotection.v4.content.ChangedRegionsModel
	(*ClusterInfo)(nil),                                       // 6: com.nutanix.dataprotection.v4.content.ClusterInfo
	(*RegionTypeMessage)(nil),                                 // 7: com.nutanix.dataprotection.v4.content.RegionTypeMessage
	(*VmDiskRecoveryPointClusterDiscoverSpec)(nil),            // 8: com.nutanix.dataprotection.v4.content.VmDiskRecoveryPointClusterDiscoverSpec
	(*VmRecoveryPointChangedRegionsComputeSpec)(nil),          // 9: com.nutanix.dataprotection.v4.content.VmRecoveryPointChangedRegionsComputeSpec
	(*VolumeGroupDiskRecoveryPointClusterDiscoverSpec)(nil),   // 10: com.nutanix.dataprotection.v4.content.VolumeGroupDiskRecoveryPointClusterDiscoverSpec
	(*VolumeGroupRecoveryPointChangedRegionsComputeSpec)(nil), // 11: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointChangedRegionsComputeSpec
	(*error1.ErrorResponse)(nil),                              // 12: com.nutanix.dataprotection.v4.error.ErrorResponse
	(*response.ApiResponseMetadata)(nil),                      // 13: com.nutanix.common.v1.response.ApiResponseMetadata
	(*config.IPAddress)(nil),                                  // 14: com.nutanix.common.v1.config.IPAddress
}
var file_com_nutanix_dataprotection_v4_content_content_proto_depIdxs = []int32{
	0,  // 0: com.nutanix.dataprotection.v4.content.ChangedRegion.region_type:type_name -> com.nutanix.dataprotection.v4.content.RegionTypeMessage.RegionType
	2,  // 1: com.nutanix.dataprotection.v4.content.ChangedRegionArrayWrapper.value:type_name -> com.nutanix.dataprotection.v4.content.ChangedRegion
	12, // 2: com.nutanix.dataprotection.v4.content.ErrorResponseWrapper.value:type_name -> com.nutanix.dataprotection.v4.error.ErrorResponse
	3,  // 3: com.nutanix.dataprotection.v4.content.ChangedRegionsModel.changed_region_array_data:type_name -> com.nutanix.dataprotection.v4.content.ChangedRegionArrayWrapper
	4,  // 4: com.nutanix.dataprotection.v4.content.ChangedRegionsModel.error_response_data:type_name -> com.nutanix.dataprotection.v4.content.ErrorResponseWrapper
	13, // 5: com.nutanix.dataprotection.v4.content.ChangedRegionsModel.metadata:type_name -> com.nutanix.common.v1.response.ApiResponseMetadata
	14, // 6: com.nutanix.dataprotection.v4.content.ClusterInfo.redirect_ip:type_name -> com.nutanix.common.v1.config.IPAddress
	1,  // 7: com.nutanix.dataprotection.v4.content.VmDiskRecoveryPointClusterDiscoverSpec.base:type_name -> com.nutanix.dataprotection.v4.content.BaseRecoveryPointSpec
	8,  // 8: com.nutanix.dataprotection.v4.content.VmRecoveryPointChangedRegionsComputeSpec.base:type_name -> com.nutanix.dataprotection.v4.content.VmDiskRecoveryPointClusterDiscoverSpec
	1,  // 9: com.nutanix.dataprotection.v4.content.VolumeGroupDiskRecoveryPointClusterDiscoverSpec.base:type_name -> com.nutanix.dataprotection.v4.content.BaseRecoveryPointSpec
	10, // 10: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointChangedRegionsComputeSpec.base:type_name -> com.nutanix.dataprotection.v4.content.VolumeGroupDiskRecoveryPointClusterDiscoverSpec
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_com_nutanix_dataprotection_v4_content_content_proto_init() }
func file_com_nutanix_dataprotection_v4_content_content_proto_init() {
	if File_com_nutanix_dataprotection_v4_content_content_proto != nil {
		return
	}
	file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes[4].OneofWrappers = []any{
		(*ChangedRegionsModel_ChangedRegionArrayData)(nil),
		(*ChangedRegionsModel_ErrorResponseData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_content_content_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_content_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_nutanix_dataprotection_v4_content_content_proto_goTypes,
		DependencyIndexes: file_com_nutanix_dataprotection_v4_content_content_proto_depIdxs,
		EnumInfos:         file_com_nutanix_dataprotection_v4_content_content_proto_enumTypes,
		MessageInfos:      file_com_nutanix_dataprotection_v4_content_content_proto_msgTypes,
	}.Build()
	File_com_nutanix_dataprotection_v4_content_content_proto = out.File
	file_com_nutanix_dataprotection_v4_content_content_proto_goTypes = nil
	file_com_nutanix_dataprotection_v4_content_content_proto_depIdxs = nil
}
