//
// Generated file com/nutanix/dataprotection/v4/content.proto.
//
// Product version: 16.9.0-SNAPSHOT
//
// Part of the Nutanix Data Proetction gRPC APIs
//
// (c) 2024 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: com/nutanix/dataprotection/v4/content/VolumeGroupRecoveryPointComputeChangedRegions_service.proto

package content

import (
	_ "github.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/dataprotection/v4"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeGroupRecoveryPointComputeChangedRegionsArg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The external identifier that can be used to retrieve the Recovery point using its URL.
	RecoveryPointExtId string `protobuf:"bytes,2001,opt,name=recovery_point_ext_id,json=recoveryPointExtId,proto3" json:"recovery_point_ext_id,omitempty"`
	// External identifier of the Volume Group recovery point.
	VolumeGroupRecoveryPointExtId string `protobuf:"bytes,2002,opt,name=volume_group_recovery_point_ext_id,json=volumeGroupRecoveryPointExtId,proto3" json:"volume_group_recovery_point_ext_id,omitempty"`
	// Disk Recovery point Identifier.
	ExtId string `protobuf:"bytes,2003,opt,name=ext_id,json=extId,proto3" json:"ext_id,omitempty"`
	// VolumeGroup Compute Changed Regions Request body [referenceRecoveryPointExtId, referenceVolumeGroupRecoveryPointExtId, referenceDiskRecoveryPointExtId, offset, length]
	Body          *VolumeGroupRecoveryPointChangedRegionsComputeSpec `protobuf:"bytes,2004,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) Reset() {
	*x = VolumeGroupRecoveryPointComputeChangedRegionsArg{}
	mi := &file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroupRecoveryPointComputeChangedRegionsArg) ProtoMessage() {}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroupRecoveryPointComputeChangedRegionsArg.ProtoReflect.Descriptor instead.
func (*VolumeGroupRecoveryPointComputeChangedRegionsArg) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) GetRecoveryPointExtId() string {
	if x != nil {
		return x.RecoveryPointExtId
	}
	return ""
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) GetVolumeGroupRecoveryPointExtId() string {
	if x != nil {
		return x.VolumeGroupRecoveryPointExtId
	}
	return ""
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) GetExtId() string {
	if x != nil {
		return x.ExtId
	}
	return ""
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsArg) GetBody() *VolumeGroupRecoveryPointChangedRegionsComputeSpec {
	if x != nil {
		return x.Body
	}
	return nil
}

// message containing all attributes expected in the volumeGroupRecoveryPointComputeChangedRegions response
type VolumeGroupRecoveryPointComputeChangedRegionsRet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// field containing expected response content
	Content *ChangedRegionsModel `protobuf:"bytes,999,opt,name=content,proto3" json:"content,omitempty"`
	// map containing headers expected in response
	Reserved      map[string]string `protobuf:"bytes,1000,rep,name=reserved,proto3" json:"reserved,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsRet) Reset() {
	*x = VolumeGroupRecoveryPointComputeChangedRegionsRet{}
	mi := &file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeGroupRecoveryPointComputeChangedRegionsRet) ProtoMessage() {}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsRet) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeGroupRecoveryPointComputeChangedRegionsRet.ProtoReflect.Descriptor instead.
func (*VolumeGroupRecoveryPointComputeChangedRegionsRet) Descriptor() ([]byte, []int) {
	return file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsRet) GetContent() *ChangedRegionsModel {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *VolumeGroupRecoveryPointComputeChangedRegionsRet) GetReserved() map[string]string {
	if x != nil {
		return x.Reserved
	}
	return nil
}

var File_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto protoreflect.FileDescriptor

const file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDesc = "" +
	"\n" +
	"acom/nutanix/dataprotection/v4/content/VolumeGroupRecoveryPointComputeChangedRegions_service.proto\x12%com.nutanix.dataprotection.v4.content\x1a/com/nutanix/dataprotection/v4/api_version.proto\x1a7com/nutanix/dataprotection/v4/http_method_options.proto\x1a3com/nutanix/dataprotection/v4/content/content.proto\"\xb9\x02\n" +
	"0VolumeGroupRecoveryPointComputeChangedRegionsArg\x122\n" +
	"\x15recovery_point_ext_id\x18\xd1\x0f \x01(\tR\x12recoveryPointExtId\x12J\n" +
	"\"volume_group_recovery_point_ext_id\x18\xd2\x0f \x01(\tR\x1dvolumeGroupRecoveryPointExtId\x12\x16\n" +
	"\x06ext_id\x18\xd3\x0f \x01(\tR\x05extId\x12m\n" +
	"\x04body\x18\xd4\x0f \x01(\v2X.com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointChangedRegionsComputeSpecR\x04body\"\xcb\x02\n" +
	"0VolumeGroupRecoveryPointComputeChangedRegionsRet\x12U\n" +
	"\acontent\x18\xe7\a \x01(\v2:.com.nutanix.dataprotection.v4.content.ChangedRegionsModelR\acontent\x12\x82\x01\n" +
	"\breserved\x18\xe8\a \x03(\v2e.com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet.ReservedEntryR\breserved\x1a;\n" +
	"\rReservedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xef\x03\n" +
	"4VolumeGroupRecoveryPointComputeChangedRegionsService\x12\xa5\x03\n" +
	"-volumeGroupRecoveryPointComputeChangedRegions\x12W.com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsArg\x1aW.com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet\"\xc1\x01\xc2>\xbd\x01\n" +
	"\xba\x01/dataprotection/v4/content/recovery-points/{recoveryPointExtId}/volume-group-recovery-points/{volumeGroupRecoveryPointExtId}/disk-recovery-points/{extId}/$actions/compute-changed-regions\x1a\x0f\x82}\f\n" +
	"\x014\x12\x010\x1a\x01a\"\x011Bz\n" +
	"%com.nutanix.dataprotection.v4.contentP\x01ZOgithub.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/dataprotection/v4/contentb\x06proto3"

var (
	file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescOnce sync.Once
	file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescData []byte
)

func file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescGZIP() []byte {
	file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescOnce.Do(func() {
		file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDesc)))
	})
	return file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDescData
}

var file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_goTypes = []any{
	(*VolumeGroupRecoveryPointComputeChangedRegionsArg)(nil), // 0: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsArg
	(*VolumeGroupRecoveryPointComputeChangedRegionsRet)(nil), // 1: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet
	nil, // 2: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet.ReservedEntry
	(*VolumeGroupRecoveryPointChangedRegionsComputeSpec)(nil), // 3: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointChangedRegionsComputeSpec
	(*ChangedRegionsModel)(nil),                               // 4: com.nutanix.dataprotection.v4.content.ChangedRegionsModel
}
var file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_depIdxs = []int32{
	3, // 0: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsArg.body:type_name -> com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointChangedRegionsComputeSpec
	4, // 1: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet.content:type_name -> com.nutanix.dataprotection.v4.content.ChangedRegionsModel
	2, // 2: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet.reserved:type_name -> com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet.ReservedEntry
	0, // 3: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsService.volumeGroupRecoveryPointComputeChangedRegions:input_type -> com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsArg
	1, // 4: com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsService.volumeGroupRecoveryPointComputeChangedRegions:output_type -> com.nutanix.dataprotection.v4.content.VolumeGroupRecoveryPointComputeChangedRegionsRet
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_init()
}
func file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_init() {
	if File_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto != nil {
		return
	}
	file_com_nutanix_dataprotection_v4_content_content_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDesc), len(file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_goTypes,
		DependencyIndexes: file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_depIdxs,
		MessageInfos:      file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_msgTypes,
	}.Build()
	File_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto = out.File
	file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_goTypes = nil
	file_com_nutanix_dataprotection_v4_content_VolumeGroupRecoveryPointComputeChangedRegions_service_proto_depIdxs = nil
}
