//
// Generated file com/nutanix/common/v1/response/response.proto.
//
// Product version: 16.9.0-SNAPSHOT
//
// Part of the Nutanix Data Proetction gRPC APIs
//
// (c) 2024 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: com/nutanix/common/v1/response/response.proto

package response

import (
	config "github.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/common/v1/config"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1001,opt,name=href,proto3" json:"href,omitempty"`
	Rel           string                 `protobuf:"bytes,1002,opt,name=rel,proto3" json:"rel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiLink) Reset() {
	*x = ApiLink{}
	mi := &file_com_nutanix_common_v1_response_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiLink) ProtoMessage() {}

func (x *ApiLink) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_response_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiLink.ProtoReflect.Descriptor instead.
func (*ApiLink) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_response_response_proto_rawDescGZIP(), []int{0}
}

func (x *ApiLink) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *ApiLink) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

type ApiResponseMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Flags                 []*config.Flag         `protobuf:"bytes,1001,rep,name=flags,proto3" json:"flags,omitempty"`
	Links                 []*ApiLink             `protobuf:"bytes,1002,rep,name=links,proto3" json:"links,omitempty"`
	TotalAvailableResults int32                  `protobuf:"varint,1003,opt,name=total_available_results,json=totalAvailableResults,proto3" json:"total_available_results,omitempty"`
	Messages              []*config.Message      `protobuf:"bytes,1004,rep,name=messages,proto3" json:"messages,omitempty"`
	ExtraInfo             []*config.KVPair       `protobuf:"bytes,1005,rep,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ApiResponseMetadata) Reset() {
	*x = ApiResponseMetadata{}
	mi := &file_com_nutanix_common_v1_response_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMetadata) ProtoMessage() {}

func (x *ApiResponseMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_com_nutanix_common_v1_response_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMetadata.ProtoReflect.Descriptor instead.
func (*ApiResponseMetadata) Descriptor() ([]byte, []int) {
	return file_com_nutanix_common_v1_response_response_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponseMetadata) GetFlags() []*config.Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ApiResponseMetadata) GetLinks() []*ApiLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ApiResponseMetadata) GetTotalAvailableResults() int32 {
	if x != nil {
		return x.TotalAvailableResults
	}
	return 0
}

func (x *ApiResponseMetadata) GetMessages() []*config.Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ApiResponseMetadata) GetExtraInfo() []*config.KVPair {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

var File_com_nutanix_common_v1_response_response_proto protoreflect.FileDescriptor

const file_com_nutanix_common_v1_response_response_proto_rawDesc = "" +
	"\n" +
	"-com/nutanix/common/v1/response/response.proto\x12\x1ecom.nutanix.common.v1.response\x1a)com/nutanix/common/v1/config/config.proto\"1\n" +
	"\aApiLink\x12\x13\n" +
	"\x04href\x18\xe9\a \x01(\tR\x04href\x12\x11\n" +
	"\x03rel\x18\xea\a \x01(\tR\x03rel\"\xd3\x02\n" +
	"\x13ApiResponseMetadata\x129\n" +
	"\x05flags\x18\xe9\a \x03(\v2\".com.nutanix.common.v1.config.FlagR\x05flags\x12>\n" +
	"\x05links\x18\xea\a \x03(\v2'.com.nutanix.common.v1.response.ApiLinkR\x05links\x127\n" +
	"\x17total_available_results\x18\xeb\a \x01(\x05R\x15totalAvailableResults\x12B\n" +
	"\bmessages\x18\xec\a \x03(\v2%.com.nutanix.common.v1.config.MessageR\bmessages\x12D\n" +
	"\n" +
	"extra_info\x18\xed\a \x03(\v2$.com.nutanix.common.v1.config.KVPairR\textraInfoBl\n" +
	"\x1ecom.nutanix.common.v1.responseP\x01ZHgithub.com/alfaz-ahmed/cbt-grpc-go-client/com/nutanix/common/v1/responseb\x06proto3"

var (
	file_com_nutanix_common_v1_response_response_proto_rawDescOnce sync.Once
	file_com_nutanix_common_v1_response_response_proto_rawDescData []byte
)

func file_com_nutanix_common_v1_response_response_proto_rawDescGZIP() []byte {
	file_com_nutanix_common_v1_response_response_proto_rawDescOnce.Do(func() {
		file_com_nutanix_common_v1_response_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_com_nutanix_common_v1_response_response_proto_rawDesc), len(file_com_nutanix_common_v1_response_response_proto_rawDesc)))
	})
	return file_com_nutanix_common_v1_response_response_proto_rawDescData
}

var file_com_nutanix_common_v1_response_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_com_nutanix_common_v1_response_response_proto_goTypes = []any{
	(*ApiLink)(nil),             // 0: com.nutanix.common.v1.response.ApiLink
	(*ApiResponseMetadata)(nil), // 1: com.nutanix.common.v1.response.ApiResponseMetadata
	(*config.Flag)(nil),         // 2: com.nutanix.common.v1.config.Flag
	(*config.Message)(nil),      // 3: com.nutanix.common.v1.config.Message
	(*config.KVPair)(nil),       // 4: com.nutanix.common.v1.config.KVPair
}
var file_com_nutanix_common_v1_response_response_proto_depIdxs = []int32{
	2, // 0: com.nutanix.common.v1.response.ApiResponseMetadata.flags:type_name -> com.nutanix.common.v1.config.Flag
	0, // 1: com.nutanix.common.v1.response.ApiResponseMetadata.links:type_name -> com.nutanix.common.v1.response.ApiLink
	3, // 2: com.nutanix.common.v1.response.ApiResponseMetadata.messages:type_name -> com.nutanix.common.v1.config.Message
	4, // 3: com.nutanix.common.v1.response.ApiResponseMetadata.extra_info:type_name -> com.nutanix.common.v1.config.KVPair
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_com_nutanix_common_v1_response_response_proto_init() }
func file_com_nutanix_common_v1_response_response_proto_init() {
	if File_com_nutanix_common_v1_response_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_com_nutanix_common_v1_response_response_proto_rawDesc), len(file_com_nutanix_common_v1_response_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_nutanix_common_v1_response_response_proto_goTypes,
		DependencyIndexes: file_com_nutanix_common_v1_response_response_proto_depIdxs,
		MessageInfos:      file_com_nutanix_common_v1_response_response_proto_msgTypes,
	}.Build()
	File_com_nutanix_common_v1_response_response_proto = out.File
	file_com_nutanix_common_v1_response_response_proto_goTypes = nil
	file_com_nutanix_common_v1_response_response_proto_depIdxs = nil
}
